version: '2'

networks:
  basic:

services:
  edu_mongodb:
    image: vantam010189/edu_mongodb:1.0
    container_name: edu_mogodb
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    networks:
        - basic
  edu_api:
    image: edu_api:1.0
    container_name: edu_api
    restart: always
    ports:
      - "127.0.0.1:8083:8083"
    networks:
        - basic
    depends_on:
      - edu_mongodb