export const LOAD_ALL_PROVINCE = 'LOAD_ALL_PROVINCE';
export const DELETE_PROVINCE = 'DELETE_PROVINCE';
export const ADD_PROVINCE = 'ADD_PROVINCE';
export const UPDATE_PROVINCE = 'UPDATE_PROVINCE';
export const UPDATE_STATUS = 'UPDATE_STATUS';