export const LOAD_ALL_SUBJECTGROUP = 'LOAD_ALL_SUBJECTGROUP';
export const DELETE_SUBJECTGROUP = 'DELETE_SUBJECTGROUP';
export const ADD_SUBJECTGROUP = 'ADD_SUBJECTGROUP';
export const UPDATE_SUBJECTGROUP = 'UPDATE_SUBJECTGROUP';
export const UPDATE_STATUS = 'UPDATE_STATUS';